@APIControllerPlugin_HostAddress = http://localhost:5027

GET {{APIControllerPlugin_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{APIControllerPlugin_HostAddress}}/ProductionSystem/Command
Content-Type: application/json

{
	"Name": "StartProduction",
	"Parameters": {
		"orderId": "1234",
		"priority": "high"
	}
}

###
